In [1]:
import numpy as np

# Creating Basic Array

In [17]:
# To create a NumPy array, you can use the function np.array():
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [27]:
# To create an arry filled with O's or 1's:
a = np.zeros(10)
b = np.ones(10)
print(a,b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
x = np.ones(2, dtype=np.int64)
x

In [36]:
np.empty(2)

array([0., 0.])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(2, 13,2)

array([ 2,  4,  6,  8, 10, 12])

In [50]:
np.linspace(0, 9, num=4)

array([0., 3., 6., 9.])

# Adding, Removing and Sorting elements

In [66]:
# This section covers np.sort(), np.concatenate()

arr = np.array([2, 3, 1, 7, 5, 10, 4, 6, 8, 9])
arr.sort()
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [67]:
rev_arr = arr[::-1]
print(rev_arr)

[10  9  8  7  6  5  4  3  2  1]


In [64]:
arr = np.array([2, 3, 1, 7, 5, 10, 4, 6, 8, 9])
copy_arr = np.sort(arr)[::-1]
print(copy_arr)

[10  9  8  7  6  5  4  3  2  1]


In [68]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate((x, y), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# shape and size of an array

In [95]:
#This section covers ndarray.ndim, ndarray.size, ndarray.shape

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [96]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [98]:
x = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])
x.ndim

3

In [99]:
x.size

24

In [100]:
x.shape

(2, 3)

#  Reshape an array

In [107]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [108]:
b = a.reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# convert a 1D array into a 2D array

In [118]:
#This section covers np.newaxis, np.expand_dims

a = np.array([1, 2, 3, 4])
a.shape

(4,)

In [119]:
a

array([1, 2, 3, 4])

In [120]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 4)

In [121]:
row_vector

array([[1, 2, 3, 4]])

In [122]:
col_vector = a[:, np.newaxis]
col_vector.shape

(4, 1)

In [123]:
col_vector

array([[1],
       [2],
       [3],
       [4]])

In [125]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [126]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [127]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [128]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [129]:
c

array([[1, 2, 3, 4, 5, 6]])

# Indexing and slicing

In [132]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
data[1]

2

In [134]:
data[0:3]

array([1, 2, 3])

In [135]:
data[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
data[-2:]

array([8, 9])

In [138]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [142]:
print(a [a < 6])

[1 2 3 4 5]


In [143]:
print(a [a > 6])

[ 7  8  9 10 11 12]


In [146]:
print(a [a%3 == 0])

[ 3  6  9 12]


In [147]:
c = a[(a > 3) & (a < 7)]
print(c)

[4 5 6]


In [148]:
cond1 = a[(a%2 == 0) | (a%3 == 0)]
print(cond1)

[ 2  3  4  6  8  9 10 12]


In [151]:
cond2 = (a > 5) | (a == 5)
print(cond2)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [152]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [159]:
b = np.nonzero(a <= 6)
print(b)

(array([0, 0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 3, 0, 1], dtype=int64))


In [160]:
list_of_coordinates= list(zip(b[0], b[1]))
for x in list_of_coordinates:
    print(x)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)


In [161]:
print(a[b])

[1 2 3 4 5 6]


# create an array from existing data 

In [162]:
#This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [164]:
a1 = np.array([[1, 1],
                [2, 2]])
a2 = np.array([[3, 3],
                [4, 4]])

In [166]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [167]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [169]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [170]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [173]:
np.hsplit(x, (3, 6))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [174]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [175]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [176]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [183]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [184]:
# Using the copy method will make a complete copy of the array and its data (a deep copy)
b2 = a.copy()

In [185]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [186]:
x = b2[0, :]
x

array([99,  2,  3,  4])

In [187]:
x[0] = 1
x

array([1, 2, 3, 4])

In [188]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [189]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#  Basic array operations

In [195]:
# This section covers addition, subtraction, multiplication, division, and more
data = np.array([4, 6])
data

array([4, 6])

In [196]:
ones = np.ones(2, dtype=int)
ones

array([1, 1])

In [197]:
data + ones

array([5, 7])

In [198]:
data - ones

array([3, 5])

In [200]:
data * data

array([16, 36])

In [202]:
data / ones

array([4., 6.])

In [203]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [206]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [207]:
b.sum(axis=0)

array([3, 3])

In [205]:
b.sum(axis=1)

array([2, 4])

# Broadcasting 

In [208]:
# NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting.
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

# More useful array operations 

In [209]:
# his section covers maximum, minimum, sum, mean, product, standard deviation, and more
data.max()

2.0

In [210]:
data.min()

1.0

In [211]:
data.sum()

3.0

In [212]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [213]:
a.sum()

4.8595784

In [214]:
a.min()

0.05093587

In [216]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# Creating matrices 

In [217]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [219]:
data[1, 1]

4

In [220]:
data[1:3] 

array([[3, 4]])

In [230]:
data[0:2, 0]

array([1, 3])

In [233]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [241]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [242]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [247]:
# the simplest way to generate random numbers
rng = np.random.default_rng(0)
rng.random((3, 3))

array([[0.63696169, 0.26978671, 0.04097352],
       [0.01652764, 0.81327024, 0.91275558],
       [0.60663578, 0.72949656, 0.54362499]])

# Generating random numbers 

In [250]:
rng.integers(5, size=(2, 4))

array([[0, 2, 0, 1],
       [2, 2, 2, 0]], dtype=int64)

# unique items and counts 

In [254]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [255]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [256]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [266]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [9, 10, 11, 12]] )

In [267]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [268]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [271]:
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 3]
[2 1 1]


# Transposing and reshaping a matrix 

In [284]:
#This section covers arr.reshape(), arr.transpose(), arr.T()
data = np.array([1, 2, 3, 4, 5, 6])
print(data)

[1 2 3 4 5 6]


In [285]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [286]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [287]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [288]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

# Reverse an array

In [289]:
#This section covers np.flip
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [291]:
reversed_arr = np.flip(arr)
print("Reversed Array: ", reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [292]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [293]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [294]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [296]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [297]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [305]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [306]:
arr_2d[:,2] = np.flip(arr_2d[:,2])
print(arr_2d)

[[ 1  2 11  4]
 [ 5  6  7  8]
 [ 9 10  3 12]]


# Reshaping and flattening multidimensional arrays

In [318]:
#This section covers .flatten(), ravel()
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [319]:
#When you use flatten, changes to your new array won’t change the parent array
y = x.flatten()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [321]:
y[0] = 99
y

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [320]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [322]:
# when you use ravel, the changes you make to the new array will affect the parent array.
a2 = x.ravel()
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [323]:
a2[0] = 99
x

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [324]:
a2

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# access the docstring for more information

In [325]:
#This section covers help(), ?, ??

help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [328]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [329]:
In [1]: a?

# Working with mathematical formulas

In [335]:
# mean square error formula

predictions = np.array([1, 1, 1])
predictions

array([1, 1, 1])

In [336]:
labels = np.array([1, 2, 3])
labels

array([1, 2, 3])

In [341]:
error = (1/3) * np.sum(np.square(predictions - labels))
error

1.6666666666666665

# Save and load NumPy objects

In [343]:
#This section covers np.save, np.savez, np.savetxt, np.load, np.loadtxt
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [344]:
np.save('filename', a)

In [345]:
b = np.load('filename.npy')
b

array([1, 2, 3, 4, 5, 6])

In [346]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
csv_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [347]:
np.savetxt('new_file.csv', csv_arr)

In [350]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Numpy Mathematical Functions 

In [354]:
a = np.array([1.7, 2.1, 3.5, 4.6, 5.5, 6.1])
a

array([1.7, 2.1, 3.5, 4.6, 5.5, 6.1])

In [355]:
np.rint(a)

array([2., 2., 4., 5., 6., 6.])

In [357]:
np.fix(a)

array([1., 2., 3., 4., 5., 6.])

In [366]:
in_array = np.array([1, 3, 5])
print ("Input array : ", in_array)

Input array :  [1 3 5]


In [359]:
out_array = np.exp(in_array)
print ("Output array : ", out_array)

Output array :  [  2.71828183  20.08553692 148.4131591 ]


In [367]:
in_array = np.array([.5, 1.5, 2.5, 3.5, 4.5, 10.1])
in_array

array([ 0.5,  1.5,  2.5,  3.5,  4.5, 10.1])

In [368]:
np.ceil(in_array)

array([ 1.,  2.,  3.,  4.,  5., 11.])

In [369]:
in_array = np.array([.53, 1.54, .71])
in_array

array([0.53, 1.54, 0.71])

In [371]:
np.trunc(in_array)

array([0., 1., 0.])

#  Misc.

In [378]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [380]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [381]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [382]:
x = np.arange(8.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [383]:
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [384]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [385]:
a.diagonal()

array([0, 3])

In [389]:
a.diagonal(1)

array([1])

In [391]:
x = np.array([[2, 2, 6],[1, 3, 6],[1, 0, 1]])
x

array([[2, 2, 6],
       [1, 3, 6],
       [1, 0, 1]])

In [393]:
x.item(4)

3

In [394]:
a = np.array([4, 3, 5, 7, 6, 8])
a

array([4, 3, 5, 7, 6, 8])

In [397]:
b = np.array([0, 1, 5])
b

array([0, 1, 5])

In [398]:
np.take(a, b)

array([4, 3, 8])

In [399]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [400]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [402]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [404]:
np.mean(a)

2.5

In [405]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [407]:
np.std(a)

1.118033988749895

In [408]:
c = np.array([[1, 2], [3, 4]])
c

array([[1, 2],
       [3, 4]])

In [409]:
np.var(a)

1.25

In [411]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [412]:
np.cross(x, y)

array([-3,  6, -3])